
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2
monitor = HDMI-A-1, 1920x1080@120, 0x0, 1
monitor = eDP-1, 1920x1080@120, 1920x0, 1
monitor=eDP-1, disable

workspace = 1,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 2,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 3,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 4,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 5,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:1,gapsout:8
workspace = 6,monitor:HDMI-A-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 7,monitor:eDP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 8,monitor:eDP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 9,monitor:eDP-1,rounding:true,decorate:true,gapsin:0,gapsout:0
workspace = 10,monitor:eDP-1,rounding:true,decorate:true,gapsin:0,gapsout:0

