local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
	s("cpp", {
		t({
			"/*",
			"    @author : vineet singh",
			"*/",
			"",
			"#include <bits/stdc++.h>",
			"#include <iostream>",
			"#include <string>",
			"#include <vector>",
			"",
			"#define int long long",
			"#define uint unsigned long long",
			"#define vi vector<int>",
			"#define vvi vector<vi>",
			"#define vb vector<bool>",
			"#define vvb vector<vb>",
			"#define fr(i, n) for (int i = 0; i < (n); i++)",
			"#define rep(i, a, n) for (int i = (a); i <= (n); i++)",
			'#define dbg(var) cout << #var << "=" << var << " "',
			"#define srt(v) sort(v.begin(), v.end())         // sort",
			"#define mxe(v) *max_element(v.begin(), v.end()) // find max element in vector",
			"#define mne(v) *min_element(v.begin(), v.end()) // find min element in vector",
			"#define unq(v) v.resize(distance(v.begin(), unique(v.begin(), v.end())));",
			"",
			"using namespace std;",
			"",
			"void solve() {",
		}),
		i(1, "  // your code here"),
		t({
			"",
			"}",
			"",
			"void online() {",
			"#ifndef ONLINE_JUDGE",
			'  freopen("input.txt", "r", stdin);',
			'  freopen("output.txt", "w", stdout);',
			"#endif",
			"}",
			"int32_t main() {",
			"",
			"  ios_base::sync_with_stdio(false);",
			"  cin.tie(NULL);",
			"  online();",
			"  int T = 1;",
			"  cin >> T;",
			"  while (T--) {",
			"    solve();",
			"  }",
			"  return 0;",
			"}",
		}),
	}),
}
