# font_family    Meslo LGM Nerd Font
font_family    Monaco
# font_family    Montserrat
font_size 18
scrollback_lines 2000
wheel_scroll_min_lines 1
initial_window_width  20c
initial_window_height 10c
# window_padding_width 7

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style powerline
tab_bar_align left
tab_powerline_style slanted
tab_activity_symbol 
active_tab_font_style   bold-italic
inactive_tab_font_style normal

editor nvim 
allow_hyperlinks yes
confirm_os_window_close 0
cursor_shape block
hide_window_decorations no

background_opacity 0.8
foreground #dddddd
background #000000

include ./rose-pine-theme.conf
