include current-theme.conf

font_family monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15

background_opacity         1
dynamic_background_opacity yes
cursor_shape block


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
